---
- hosts: default
  remote_user: marco
  become: true
  vars:
   BOT_TOKEN: "{{ lookup('env','BOT_TOKEN') }}"
   DB_PASSWORD: "{{ lookup('env','DB_PASSWORD')}}"
   DB_USER: "{{ lookup('env','DB_USER')}}"
   DB_USER: "{{ lookup('env','NODE_ENV')}}"
  tasks:
  - name: Updating repositories
    command: apt-get update
  - name: Installing essential libs
    command: apt-get install -y build-essential
  - name: Installing git
    command: apt-get install -y git
  - name: Installing pip
    command: apt-get install -y python-pip
  - name: Update pip
    command: pip install --upgrade pip
  - name: Cloning project repository
    shell: git clone https://github.com/MarFerPra/teletorrent
